modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/Banjomann/Vivicraft/issues" #optional

[[mods]] #mandatory

modId="vivicraft" #mandatory

version="1.15.2-1.0.0" #mandatory

displayName="Vivicraft" #mandatory

logoFile="vivicraft_logo.png" #optional

authors="Banjomann" #optional

description='''     The base libraries and API for Vivicraft'''

[[dependencies.vivicraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.vivicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
