modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/Banjomann/Viviscription/issues" #optional

[[mods]] #mandatory

modId="viviscription" #mandatory

version="${version}" #mandatory

displayName="Viviscription" #mandatory

logoFile="logo_forgebig.png" #optional

authors="Banjomann" #optional

description='''
     From Latin roots "vivus" (alive) and "scribere" (to write).
'''

[[dependencies.viviscription]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.viviscription]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
